### ISSUE TITLE
Unhandled Exception: Unable to load asset: assets/i18n/en.json

### ISSUE THREAD

**Issue by iizvv** [ilteoood/flutter_i18n#114]
I am using yaml
![Snip20200708_80](https://user-images.githubusercontent.com/15830996/86929805-d86cf400-c168-11ea-9ee3-607a6f76f5de.png)
![image](https://user-images.githubusercontent.com/15830996/86929866-eae72d80-c168-11ea-951c-0726e4de5295.png)
![image](https://user-images.githubusercontent.com/15830996/86929906-f6d2ef80-c168-11ea-90d2-b8cc0ddbc1e0.png)

```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Unable to load asset: assets/i18n/en.json
#0      PlatformAssetBundle.load 
package:flutter/…/services/asset_bundle.dart:221
<asynchronous suspension>
#1      AssetBundle.loadString 
package:flutter/…/services/asset_bundle.dart:67
#2      CachingAssetBundle.loadString.<anonymous closure> 
package:flutter/…/services/asset_bundle.dart:162
#3      _LinkedHashMapMixin.putIfAbsent  (dart:collection-patch/compact_hash.dart:293:23)
#4      CachingAssetBundle.loadString 
package:flutter/…/services/asset_bundle.dart:162
#5      FileTranslationLoader.loadString 
package:flutter_i18n/loaders/file_translation_loader.dart:46
#6      BaseDecodeStrategy.loadFileContent 
package:flutter_i18n/…/decoders/base_decode_strategy.dart:27
#7      BaseDecodeStrategy.decode 
package:flutter_i18n/…/decoders/base_decode_strategy.dart:14
#8      FileTranslationLoader._executeStrategies.<anonymous closure> (package:flutter_i18n/lo<…>
flutter: [flutter_i18n INFO]: YAML file loaded for en
Reloaded 3 of 836 libraries in 169ms.
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Unable to load asset: assets/i18n/en.xml
#0      PlatformAssetBundle.load 
package:flutter/…/services/asset_bundle.dart:221
<asynchronous suspension>
#1      AssetBundle.loadString 
package:flutter/…/services/asset_bundle.dart:67
#2      CachingAssetBundle.loadString.<anonymous closure> 
package:flutter/…/services/asset_bundle.dart:162
#3      _LinkedHashMapMixin.putIfAbsent  (dart:collection-patch/compact_hash.dart:293:23)
#4      CachingAssetBundle.loadString 
package:flutter/…/services/asset_bundle.dart:162
#5      FileTranslationLoader.loadString 
package:flutter_i18n/loaders/file_translation_loader.dart:46
#6      BaseDecodeStrategy.loadFileContent 
package:flutter_i18n/…/decoders/base_decode_strategy.dart:27
#7      BaseDecodeStrategy.decode 
package:flutter_i18n/…/decoders/base_decode_strategy.dart:14
#8      FileTranslationLoader._executeStrategies.<anonymous closure> (package:flutter_i18n/loa<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Unable to load asset: assets/i18n/en.json
#0      PlatformAssetBundle.load 
package:flutter/…/services/asset_bundle.dart:221
<asynchronous suspension>
#1      AssetBundle.loadString 
package:flutter/…/services/asset_bundle.dart:67
#2      CachingAssetBundle.loadString.<anonymous closure> 
package:flutter/…/services/asset_bundle.dart:162
#3      _LinkedHashMapMixin.putIfAbsent  (dart:collection-patch/compact_hash.dart:293:23)
#4      CachingAssetBundle.loadString 
package:flutter/…/services/asset_bundle.dart:162
#5      FileTranslationLoader.loadString 
package:flutter_i18n/loaders/file_translation_loader.dart:46
#6      BaseDecodeStrategy.loadFileContent 
package:flutter_i18n/…/decoders/base_decode_strategy.dart:27
#7      BaseDecodeStrategy.decode 
package:flutter_i18n/…/decoders/base_decode_strategy.dart:14
#8      FileTranslationLoader._executeStrategies.<anonymous closure> (package:flutter_i18n/lo<…>
flutter: [flutter_i18n INFO]: YAML file loaded for en
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Unable to load asset: assets/i18n/en.xml
#0      PlatformAssetBundle.load 
<asynchronous suspension>
#1      AssetBundle.loadString 
package:flutter/…/services/asset_bundle.dart:67
#2      CachingAssetBundle.loadString.<anonymous closure> 
package:flutter/…/services/asset_bundle.dart:162
#3      _LinkedHashMapMixin.putIfAbsent  (dart:collection-patch/compact_hash.dart:293:23)
#4      CachingAssetBundle.loadString 
package:flutter/…/services/asset_bundle.dart:162
#5      FileTranslationLoader.loadString 
package:flutter_i18n/loaders/file_translation_loader.dart:46
#6      BaseDecodeStrategy.loadFileContent 
package:flutter_i18n/…/decoders/base_decode_strategy.dart:27
#7      BaseDecodeStrategy.decode 
package:flutter_i18n/…/decoders/base_decode_strategy.dart:14
#8      FileTranslationLoader._executeStrategies.<anonymous closure> (package:flutter_i18n/loa<…>

```

**Comment by ilteoood** [comment]
Hi,
did you tried to use the decodeStrategies parameter?

**Comment by iizvv** [comment]
I found this parameter, just about to use it, thank you very much for making such a perfect library.

**Comment by impsdc** [comment]
Hello, 

I'm trying to set up traduction with yaml file but I got errors likes above :
"Could not update files on device: FileSystemException: Cannot open file, path = '/home/psantamaria/projects/epitech/dev/app/front/assets/i18n/en.json' (OS Error: No such file or directory, errno = 2)"

![image](https://user-images.githubusercontent.com/55087969/144730264-77b67497-521e-49b4-8b37-aa7f497d4f02.png)
![image](https://user-images.githubusercontent.com/55087969/144730274-e518765d-04a2-4544-b3a8-a177cdfa0e73.png)
![image](https://user-images.githubusercontent.com/55087969/144730285-e1a05779-f253-480e-8d5f-a546d01d7d9e.png)

**Comment by ilteoood** [comment]
Hi @impsdc, have you declared the assets folder in the pubsec file?
