### ISSUE TITLE
Should default to fallback language if a file does not exist for the current locale

### ISSUE THREAD

**Issue by JMichaelYang** [ilteoood/flutter_i18n#15]
I am currently seeing crashes where the package cannot resolve the file for my current locale (set phone language to Korean for testing). In these cases, the package should default to the fallback locale.

**Comment by ilteoood** [comment]
Can you past the stacktrace?

**Comment by JMichaelYang** [comment]
```
E/flutter (11442): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Unable to load asset: assets/locales/ko.json
E/flutter (11442): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
E/flutter (11442): <asynchronous suspension>
E/flutter (11442): #1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:67:33)
E/flutter (11442): <asynchronous suspension>
E/flutter (11442): #2      CachingAssetBundle.loadString.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:162:56)
E/flutter (11442): #3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
E/flutter (11442): #4      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:162:27)
E/flutter (11442): #5      FlutterI18n._loadFile (package:flutter_i18n/flutter_i18n.dart:45:26)
E/flutter (11442): <asynchronous suspension>
E/flutter (11442): #6      FlutterI18n._loadCurrentTranslation (package:flutter_i18n/flutter_i18n.dart:32:11)
E/flutter (11442): <asynchronous suspension>
E/flutter (11442): #7      FlutterI18n.load (package:flutter_i18n/flutter_i18n.dart:23:13)
E/flutter (11442): <asynchronous suspension>
E/flutter (11442): #8      FlutterI18nDelegate.load (package:flutter_i18n/flutter_i18n_delegate.dart:26:23)
E/flutter (11442): <asynchronous suspension>
E/flutter (11442): #9      _loadAll (package:flutter/src/widgets/localizations.dart:57:49)
E/flutter (11442): #10     _LocalizationsState.load (package:flutter/src/widgets/localizations.dart:508:62)
E/flutter (11442): #11     _LocalizationsState.initState (package:flutter/src/widgets/localizations.dart:473:5)
E/flutter (11442): #12     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3830:58)
E/flutter (11442): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (11442): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
Reloaded 2 of 535 libraries in 894ms.
E/flutter (11442): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (11442): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (11442): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (11442): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (11442): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (11442): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (11442): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (11442): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (11442): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (11442): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (11442): #25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
E/flutter (11442): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (11442): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (11442): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (11442): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (11442): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (11442): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (11442): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (11442): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (11442): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (11442): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (11442): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (11442): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (11442): #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (11442): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (11442): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (11442): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (11442): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (11442): #43     ComponentElement._firstBuild (package:flutter/src/widgets/framewo
Application finished.
```

**Comment by JMichaelYang** [comment]
Working on a PR to fix this now

**Comment by JMichaelYang** [comment]
I see the `try catch` block in the `load` method, I wonder why it didn't catch this...

**Comment by JMichaelYang** [comment]
Declared in `.yml`, structure is fine (loads English file just fine)

Delegate declaration:
```
localizationsDelegates: [
          FlutterI18nDelegate(false, "en", "assets/locales"),
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
        ],
```

**Comment by JMichaelYang** [comment]
Tested again, stepping through... Worked the second time (verified that the `try catch` block is working as intended)... Weird, will close this issue but will let you know if the issue comes up again

**Comment by ilteoood** [comment]
Thank you so much for your contributions!

**Comment by williamdias** [comment]
I am having the same problem. I do not have an english file for every country code. I would like it to fallback to ``en.json``. File are being loaded correctly. 

```
await FlutterI18n.refresh(context, locale.languageCode, countryCode: locale.countryCode);
```
```
localizationsDelegates: [
        FlutterI18nDelegate(true, 'en', 'lib/assets/locales'),
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate
      ]
```
```
E/flutter (31558): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (31558): Unable to load asset: lib/assets/locales/en_US.json
E/flutter (31558): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
E/flutter (31558): <asynchronous suspension>
E/flutter (31558): #1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:67:33)
E/flutter (31558): <asynchronous suspension>
E/flutter (31558): #2      CachingAssetBundle.loadString.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:162:56)
E/flutter (31558): #3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
E/flutter (31558): #4      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:162:27)
E/flutter (31558): #5      FlutterI18n._loadFile (package:flutter_i18n/flutter_i18n.dart:45:26)
E/flutter (31558): <asynchronous suspension>
E/flutter (31558): #6      FlutterI18n._loadCurrentTranslation (package:flutter_i18n/flutter_i18n.dart:32:11)
E/flutter (31558): <asynchronous suspension>
E/flutter (31558): #7      FlutterI18n.load (package:flutter_i18n/flutter_i18n.dart:23:13)
E/flutter (31558): <asynchronous suspension>
E/flutter (31558): #8      FlutterI18nDelegate.load (package:flutter_i18n/flutter_i18n_delegate.dart:26:23)
E/flutter (31558): <asynchronous suspension>
E/flutter (31558): #9      _loadAll (package:flutter/src/widgets/localizations.dart:57:49)
E/flutter (31558): #10     _LocalizationsState.load (package:flutter/src/widgets/localizations.dart:508:62)
E/flutter (31558): #11     _LocalizationsState.initState (package:flutter/src/widgets/localizations.dart:473:5)
```
