### ISSUE TITLE
Black screen after splash screen with async main

### ISSUE THREAD

**Issue by duduf15** [ilteoood/flutter_i18n#42]
Hi, thanks for your library, I had same problem than #17 #18  #28 #29. I had tried to fix it by using your example in #17 but it's not working. Here is [my example](https://github.com/duduf15/test_i18n/blob/master/lib/main.dart), what i done wrong ? I need my main async for local storage initialize.
thanks

**Comment by ilteoood** [comment]
Hi, I'll check when I'll go back from vacation

**Comment by chaunqingren** [comment]
Using the solution provided(issue#17), black screen is resolved, but `await delegate.load(null)` is not work before runApp():
```
E/flutter ( 9428): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter ( 9428): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
E/flutter ( 9428): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
E/flutter ( 9428): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:73:7)
E/flutter ( 9428): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:86:4)
E/flutter ( 9428): #2      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:219:15)
E/flutter ( 9428): <asynchronous suspension>
E/flutter ( 9428): #3      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:67:33)
E/flutter ( 9428): <asynchronous suspension>
E/flutter ( 9428): #4      CachingAssetBundle.loadString.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:162:56)
E/flutter ( 9428): #5      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
E/flutter ( 9428): #6      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:162:27)
E/flutter ( 9428): #7      FlutterI18n._loadFile (package:flutter_i18n/flutter_i18n.dart:45:41)
E/flutter ( 9428): <asynchronous suspension>
E/flutter ( 9428): #8      FlutterI18n._loadFallback (package:flutter_i18n/flutter_i18n.dart:38:13)
E/flutter ( 9428): <asynchronous suspension>
E/flutter ( 9428): #9      FlutterI18n.load (package:flutter_i18n/flutter_i18n.dart:26:13)
E/flutter ( 9428): <asynchronous suspension>
E/flutter ( 9428): #10     FlutterI18nDelegate.load (package:flutter_i18n/flutter_i18n_delegate.dart:31:59)
E/flutter ( 9428): <asynchronous suspension>
E/flutter ( 9428): #11     main (package:flutter_app/main.dart:27:18)
E/flutter ( 9428): <asynchronous suspension>
E/flutter ( 9428): #12     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:229:25)
E/flutter ( 9428): #13     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 9428): #14     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 9428): #15     _runZoned (dart:async/zone.dart:1516:10)
E/flutter ( 9428): #16     runZoned (dart:async/zone.dart:1500:12)
E/flutter ( 9428): #17     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:221:5)
E/flutter ( 9428): #18     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
E/flutter ( 9428): #19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
E/flutter ( 9428): 
```

**Comment by chaunqingren** [comment]
In the same code, I tried the [Flutter I18N Plugin] in Android Studio (https://github.com/long1eu/flutter_i18n) to generate `i18n.dart' based on the `.arb file', replacing `FlutterI18nDelegate' with `S.delegate'without a black screen.
===============================================
同样的代码，我尝试了Android Studio中的[Flutter I18N插件](https://github.com/long1eu/flutter_i18n)，根据`.arb文件`生成`i18n.dart`的方案，将“FlutterI18nDelegate”替换为“S.delegate”不会出现黑屏。

**Comment by Shakle** [comment]
Please fix this, many thanks.

**Comment by ilteoood** [comment]
Hi guys,
I know that this seems an excuse, but I'm very busy at work in these weeks.

BTW, using the official Android emulator I see a little black screen at the application boot (~2 secs).
With these commit: https://github.com/ilteoood/flutter_i18n/commit/250d2fb85e31d1a67be29b4ebd5a66032122460b, I've changed the demo app to avoid it.
Is it happening to you, even with these solution? If yes, can you send to me an example of your implementation?

Thank you so much,
Matteo

**Comment by juncaixinchi** [comment]
you can try my repo which add an option to set default Locale, no black screen 

https://github.com/juncaixinchi/flutter_i18n

code example

```dart
import 'package:flutter/material.dart';
import 'package:intl/intl_standalone.dart';

import 'package:flutter_i18n/flutter_i18n_delegate.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() async {
  // set default language or load from configs
  String lan = 'en';
  if (lan == null) {
    // load system locale if lan == null
    final String systemLocale = await findSystemLocale();
    final List<String> systemLocaleSplitted = systemLocale.split('_');
    lan = systemLocaleSplitted[0];
  }

  final FlutterI18nDelegate flutterI18nDelegate = FlutterI18nDelegate(
    useCountryCode: false,
    fallbackFile: 'en',
    path: 'assets/locales',
    defaultLocale: Locale(lan),
  );

  // preload default locale to avoid black screen
  await flutterI18nDelegate.load(null);

  runApp(MyApp(flutterI18nDelegate));
}

class MyApp extends StatelessWidget {
  final FlutterI18nDelegate flutterI18nDelegate;

  MyApp(this.flutterI18nDelegate);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text('Test'),
        ),
      ),
      localizationsDelegates: [
        flutterI18nDelegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate
      ],
    );
  }
}
```

**Comment by ilteoood** [comment]
@juncaixinchi you used the same solution that I provided to the example app: an async main.
I don't like your fallback language management. As said in #49, I'll implement this feature in the next release if you like!

Matteo

**Comment by ilteoood** [comment]
@chaunqingren, @duduf15 , @Shakle: as asked (here)[https://github.com/ilteoood/flutter_i18n/issues/42#issuecomment-529610049], have you tried the solution provided inside the example app?

**Comment by javiercbk** [comment]
In my case, here is what happened

```dart
import 'package:flutter/material.dart';
import 'package:flutter_i18n/flutter_i18n.dart';
import 'package:flutter_i18n/flutter_i18n_delegate.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

const I18N_FALLBACK_FILE = 'en';
const I18N_PATH = 'assets/i18n';

Future main() async {
  final FlutterI18nDelegate flutterI18nDelegate = FlutterI18nDelegate(
      useCountryCode: false, fallbackFile: I18N_FALLBACK_FILE, path: I18N_PATH);
  // forcedLocale: new Locale('es'));
  await flutterI18nDelegate.load(null);
  runApp(MyApp(flutterI18nDelegate));
}

class MyApp extends StatelessWidget {
  final FlutterI18nDelegate flutterI18nDelegate;

  MyApp(this.flutterI18nDelegate);
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: FlutterI18n.translate(context, "title"), // breaks the app
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.orange,
      ),
      home: MyHomePage(title: FlutterI18n.translate(context, "title")), // breaks the app
      localizationsDelegates: [
        flutterI18nDelegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate
      ],
    );
  }
}
```

I was able to use the translations without my app breaking in a `MyApp` child component, but would break when using the translations in the `MyApp` component.
