### ISSUE TITLE
Issues accesing i18n before MaterialApp

### ISSUE THREAD

**Issue by jesusrp98** [ilteoood/flutter_i18n#72]
I'm trying to access the translations before I build the `MaterialApp` widget. Is that even possible? Been tinkering with it for the last couples days without no luck :(

Here's an example of what I'd like to have:
```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print(FlutterI18n.translate(context, 'app.title'));

    return MaterialApp(
      title: 'App name',
      home: StartScreen(),
      localizationsDelegates: [
        FlutterI18nDelegate(fallbackFile: 'en'),
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate
      ],
    );
  }
}
```
Here's the output error I'm getting:
```
I/flutter ( 9319): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9319): The following NoSuchMethodError was thrown building MyApp(dirty):
I/flutter ( 9319): The getter 'decodedMap' was called on null.
I/flutter ( 9319): Receiver: null
I/flutter ( 9319): Tried calling: decodedMap
I/flutter ( 9319): 
I/flutter ( 9319): The relevant error-causing widget was:
I/flutter ( 9319):   MyApp file:///home/jesus/Documents/spacex-go/lib/main.dart:11:23
I/flutter ( 9319): 
I/flutter ( 9319): When the exception was thrown, this was the stack:
I/flutter ( 9319): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter ( 9319): #1      FlutterI18n._translateWithKeyFallback (package:flutter_i18n/flutter_i18n.dart:162:43)
I/flutter ( 9319): #2      FlutterI18n.translate (package:flutter_i18n/flutter_i18n.dart:139:26)
I/flutter ( 9319): #3      MyApp.build (package:cherry/main.dart:18:23)
I/flutter ( 9319): #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4397:28)
I/flutter ( 9319): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4329:15)
I/flutter ( 9319): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4053:5)
I/flutter ( 9319): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4312:5)
I/flutter ( 9319): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4307:5)
I/flutter ( 9319): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3297:14)
I/flutter ( 9319): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3091:12)
I/flutter ( 9319): #11     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1054:16)
I/flutter ( 9319): #12     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1025:5)
I/flutter ( 9319): #13     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:968:17)
I/flutter ( 9319): #14     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2512:19)
I/flutter ( 9319): #15     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:967:13)
I/flutter ( 9319): #16     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:848:7)
I/flutter ( 9319): #17     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:830:7)
I/flutter ( 9319): #26     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
I/flutter ( 9319): #27     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
I/flutter ( 9319): #28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
I/flutter ( 9319): (elided 8 frames from package dart:async and package dart:async-patch)
I/flutter ( 9319): 
I/flutter ( 9319): ════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by ilteoood** [comment]
Hi,
What you can do is create the delegate before MyApp, force an initial language and then translate your key.
Unfortunately, the translate method is usable only after the delegate, that load asynchronously your translation map.
